# Change this to your endpoint.
# Note: In development, `yarn watch:html` script defined in package.json overrides this with an empty string
baseurl: https://vaharoni.github.io/static-site-boilerplate

# First language is the default language
languages: ["en"]

keep_files:
  - .git
  - assets/javascripts
  - assets/stylesheets

exclude:
  - assets/javascripts
  - assets/stylesheets

# Excluding files with front matter won't work. Workaround: add rm directives in bin/build
exclude_from_localizations:
  - assets
  - CNAME

plugins:
  - jekyll-multiple-languages-plugin
